name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch: {}

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Visit Streamlit App
        run: |
          response=$(curl -X GET -s -o /dev/null -w "%{http_code}" "https://gcp-genai-zh.streamlit.app")
          if [ "$response" -eq 200 ]; then
            echo "Successfully visited Streamlit app. Status code: $response"
          else
            echo "Failed to visit Streamlit app. Status code: $response"
            exit 1
          fi